name: TPRegions
author: JC The Pants
main: com.jcwhatever.bukkit.tpregions.TPRegions
version: 0.4
depend: [jcGenerics]
commands:
    tpr:
        description: Base command for TPRegions
        usage: |
            ERROR!
    tpregions:
        description: Base command for TPRegions
        usage: |
            ERROR!