name: TPRegions
author: JCThePants
main: com.jcwhatever.bukkit.tpregions.TPRegions
version: 0.0-beta
depend: [GenericsLib]
commands:
    tpr:
        description: Base command for TPRegions
        usage: |
            ERROR!
    tpregions:
        description: Base command for TPRegions
        usage: |
            ERROR!