name: TPRegions
author: JCThePants
main: TPRegions
version: 0.0-beta
depend: [NucleusFramework]
commands:
    tpr:
        aliases: [tpregions]
        description: Base command for TPRegions
        usage: |
            ERROR!